### ISSUE TITLE
[Tracking] UI

### ISSUE THREAD

**Issue by matthunz** [actuate-rs/actuate#47]
- [ ] https://github.com/actuate-rs/actuate/issues/28
- [ ] https://github.com/actuate-rs/actuate/issues/41
- [ ] https://github.com/actuate-rs/actuate/issues/45
- [ ] https://github.com/actuate-rs/actuate/issues/23
